### ISSUE TITLE
Root transform on VRC contact receiver/sender keeps copied reference.

### ISSUE THREAD

**Issue by Lupinixx** [rurre/PumkinsAvatarTools#69]
When copying  over vrc contact receiver/sender scripts, the Root transform keeps pointing to the object from the template, and is not pointing to the newly created target.

**Comment by ShaunDreclin** [comment]
Same issue here, a fix would be greatly appreciated!

**Comment by rurre** [comment]
I'll check tomorrow if i don't forget
________________________________

**Comment by rurre** [comment]
Should be fixed in the next WIP release. You can get it on the discord later today.

**Comment by Carcosa-Hali** [comment]
This appears to still be an issue under some circumstances. I have a scene in which using Pumkin Tools to copy game objects results in all references being to the original model. This includes

- VRC Parent Constraint "Source Transform"
- Physbone "Root Transform"
- Physbone Collider "Root Transform"
- VRCFury Armature Link "Link From (Prop / Clothing)

And so on.

**Comment by rurre** [comment]
This has been sorta fixed but seems to still happen under *some circumstances*, but unless there's a consistent way to reproduce it, I don't know how to fix it.

**Comment by Carcosa-Hali** [comment]
I have a setup which quite reliably reproduces the issue.

References are always to the original model, whenever Pumkin Tools is used to copy components in the scene in which the original model was set up.
The issue persists, reliably, when the original model is turned into a prefab and used in a new scene.

I can't get it to *not* reproduce this issue.

If that's of any interest, please let me know. I understand that it's a niche issue for a free tool. Thanks for your time.

**Comment by Carcosa-Hali** [comment]
I think I've tracked down something, maybe, so tentatively I'll write it down here:

It seems that if there are

- any components on the model, which are *not* included as part of the children of the "Armature" object

then when Pumkin Tools copies the components,

- All of the components which have references, will continue to reference the original model. This includes both components *outside* of the Armature, and those that are *inside* of it.

So, my solution is to move all of my components into the Armature itself.
Maybe this is a known, or intended behaviour. Maybe I didn't read the correct part of the documentation. I apologize if so. Sorry to bother, hopefully this might be useful for someone else in future.

**Comment by rurre** [comment]
I’ll have a look when I get to working on the till next time. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
